name: 'Darshan Markdown Improver'
description: 'Improves markdown files using OpenAI'

inputs:
  repo:
    required: true
    description: 'GitHub repo URL'
  mdfile:
    required: true
    description: 'Markdown file path'
  purpose:
    required: true
    description: 'Purpose of the improvement'
  token:
    required: true
    description: 'GitHub Token for making PRs'

runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      run: ./entrypoint.sh
      env:
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
