name: "Darshan Markdown Improver"
description: "Improves a markdown file in any GitHub repo using purpose"

inputs:
  repo:
    description: "GitHub repo URL to clone"
    required: true
  mdfile:
    description: "Markdown file path to improve"
    required: true
  purpose:
    description: "Purpose of the markdown improvement"
    required: true
  token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone the action repository
      shell: bash
      run: |
        git clone https://github.com/Darshan-222004/darshan-md-improver.git improver-repo

    - name: Make entrypoint.sh executable
      shell: bash
      run: |
        chmod +x ./improver-repo/entrypoint.sh

    - name: Run improvement script
      shell: bash
      run: |
        ./improver-repo/entrypoint.sh "${{ inputs.repo }}" "${{ inputs.mdfile }}" "${{ inputs.purpose }}" "${{ inputs.token }}"

    - name: Clean up
      shell: bash
      run: |
        rm -rf improver-repo
