name: "Darshan Markdown Improver"
description: "Improves a markdown file using OpenAI API"
inputs:
  repo:
    description: "GitHub repository URL"
    required: true
  mdfile:
    description: "Markdown file path inside the repo"
    required: true
  purpose:
    description: "Purpose of improvement"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Clone Repository"
      run: |
        echo "Cloning the repo..."
        git clone ${{ inputs.repo }} repo
      shell: bash

    - name: "Install OpenAI Python Package"
      run: |
        echo "Installing OpenAI Python package..."
        pip install openai
      shell: bash

    - name: "Copy Python Script"
      run: |
        echo "Copying Python script to the cloned repo folder..."
        cp ${{ github.action_path }}/md_auto_refine.py repo/
      shell: bash

    - name: "Run Markdown Improvement Script"
      run: |
        echo "Running the script..."
        python repo/md_auto_refine.py ${{ inputs.mdfile }} ${{ inputs.purpose }}
      shell: bash
