name: 'Markdown Improver'
description: 'Improves markdown files using OpenAI API'
inputs:
  repo:
    description: 'Repository name'
    required: true
  mdfile:
    description: 'Markdown filename'
    required: true
    default: 'sample.md'
  purpose:
    description: 'Improvement goal'
    required: true
    default: 'enhance documentation'
runs:
  using: "composite"
  steps:
    - run: |
        echo "Checking files in action directory:"
        ls -la "$GITHUB_ACTION_PATH"
        chmod +x "$GITHUB_ACTION_PATH/entrypoint.sh"
        "$GITHUB_ACTION_PATH/entrypoint.sh" "${{ inputs.repo }}" "${{ inputs.mdfile }}" "${{ inputs.purpose }}" "${{ github.token }}"
      shell: bash
