name: 'Markdown Improver'
description: 'Improves markdown files using OpenAI API'
inputs:
  repo:
    required: true
  mdfile:
    required: true
  purpose:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x "$GITHUB_ACTION_PATH/entrypoint.sh"
        "$GITHUB_ACTION_PATH/entrypoint.sh" "${{ inputs.repo }}" "${{ inputs.mdfile }}" "${{ inputs.purpose }}" "${{ env.GITHUB_TOKEN }}"
      shell: bash
