name: "Improve Markdown"
description: "Improves Markdown file using OpenAI"
inputs:
  repo:
    required: true
  mdfile:
    required: true
  purpose:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout own action repo (darshan-md-improver)
      uses: actions/checkout@v4
      with:
        repository: Darshan-222004/darshan-md-improver
        path: darshan-md-improver

    - name: Run entrypoint script
      run: bash darshan-md-improver/entrypoint.sh "${{ inputs.repo }}" "${{ inputs.mdfile }}" "${{ inputs.purpose }}"
      shell: bash
