name: 'Markdown Improver'
description: 'Uses OpenAI to improve a Markdown file'

inputs:
  repo:
    required: true
  mdfile:
    required: true
  purpose:
    required: true
  token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Markdown Improver script
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh" "${{ inputs.repo }}" "${{ inputs.mdfile }}" "${{ inputs.purpose }}" "${{ inputs.token }}"
