name: "Darshan Markdown Improver"
description: "Improves a markdown file in any GitHub repo using purpose"
inputs:
  repo:
    description: 'GitHub repo URL to clone'
    required: true
  mdfile:
    description: 'Markdown file path to improve'
    required: true
  purpose:
    description: 'Purpose of the markdown improvement'
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone action repo
      run: |
        git clone https://github.com/Darshan-222004/darshan-md-improver.git improver
      shell: bash

    - name: Run improvement script
      shell: bash
      run: |
        chmod +x improver/entrypoint.sh
        ./improver/entrypoint.sh "${{ inputs.repo }}" "${{ inputs.mdfile }}" "${{ inputs.purpose }}"
