name: Improve Markdown File

on:
  workflow_dispatch:

permissions:
  contents: write  # Required for push access

jobs:
  improve-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN || github.token }}  # Updated to use GH_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install openai==1.12.0

      - name: Run Markdown Improver
        uses: Darshan-222004/darshan-md-improver@v2
        with:
          repo: https://github.com/${{ github.repository }}
          mdfile: README.md
          purpose: "introduce a programming concept"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass to script if needed

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Explicitly available for git ops
        run: |
          # Check for changes first
          if [ -z "$(git status --porcelain README.md)" ]; then
            echo "No changes to commit"
            exit 0
          fi

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📖 Docs: Auto-update $(date +'%Y-%m-%d') [skip ci]"

          # Authenticated push
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git
          git pull --rebase
          git push origin HEAD
