name: Lint Shell, YAML, Python, Markdown

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint shell script
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ./entrypoint.sh

      - name: Lint action.yml (optional)
        if: ${{ hashFiles('action.yml') != '' }}
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: action.yml

      - name: Lint markdown files
        uses: actionshub/markdownlint@main
        with:
          filesToIgnoreRegex: "sample\\.md"

      - name: Lint Python file
        uses: chartboost/ruff-action@v1
        with:
          args: check improver.py
